<a href="https://colab.research.google.com/github/truebobsuncle/IE2/blob/main/exer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

A = A * 2
print(A)

A[A > 10] = 0
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


In [2]:
import numpy as np
arr = np.random.randint(1, 101, 20)
print("Исх массив:")
print(arr)

a = arr % 5 == 0
print("\nЭл, дел на 5:")
print(arr[a])

arr[a] = -1
print("\nОбнов.массив (эл, дел на 5, зам на -1):")
print(arr)

Исх массив:
[41 49 60 17 73 57 19 96 91 34 41 86 68 68 35 68 22 56 94 53]

Эл, дел на 5:
[60 35]

Обнов.массив (эл, дел на 5, зам на -1):
[41 49 -1 17 73 57 19 96 91 34 41 86 68 68 -1 68 22 56 94 53]


In [3]:
import numpy as np
arr1 = np.random.randint(0, 51, 5)
arr2 = np.random.randint(0, 51, 5)
print(arr1)
print(arr2)

a = np.vstack([arr1, arr2])
print("\nДвумерный массив:")
print(a)

b, c = a[0, :], a[1, : ]
print("\nРазделенные массивы:")
print("Первый:", b)
print("Второй:", c)

[16 40 29 34 28]
[49 33 16 17 18]

Двумерный массив:
[[16 40 29 34 28]
 [49 33 16 17 18]]

Разделенные массивы:
Первый: [16 40 29 34 28]
Второй: [49 33 16 17 18]


In [4]:
import numpy as np
arr = np.linspace(-10, 10, 50)
print("Массив из 50 чисел от -10 до 10:")
print(arr)

total_sum = np.sum(arr)
print(f"\nСумма всех элементов: {total_sum}")
plus_sum = np.sum(arr[arr > 0])
print(f"Сумма положительных элементов: {plus_sum:.4f}")
minus_sum = np.sum(arr[arr < 0])
print(f"Сумма отрицательных элементов: {minus_sum:.4f}")

Массив из 50 чисел от -10 до 10:
[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]

Сумма всех элементов: 7.105427357601002e-15
Сумма положительных элементов: 127.5510
Сумма отрицательных элементов: -127.5510


In [5]:
import numpy as np
edmat = np.eye(4)
print("Единичная матрица 4x4:")
print(edmat)

d = np.diag([5, 10, 15, 20])
print("\nДиагональная матрица:")
print(d)

sum_edmat = np.sum(edmat)
sum_d = np.sum(d)

print(f"\nСумма элементов единичной матрицы: {sum_edmat}")
print(f"Сумма элементов диагональной матрицы: {sum_d}")
print(f"Разница: {sum_d - sum_edmat}")

Единичная матрица 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Диагональная матрица:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50
Разница: 46.0


In [6]:
import numpy as np
A = np.random.randint(1, 21, (3, 3))
B = np.random.randint(1, 21, (3, 3))

print("Матрица А:")
print(A)
print("\nМатрица В:")
print(B)

smatr = A + B
print("\nСумма А + В:")
print(smatr)

raznat = A - B
print("\nРазность А - В:")
print(raznat)

poelement = A * B
print("\nПоэлементное произведение:")
print(poelement)

Матрица А:
[[ 5  5 13]
 [17  5 18]
 [15 12  5]]

Матрица В:
[[ 5 14 12]
 [12  5  6]
 [14 20 16]]

Сумма А + В:
[[10 19 25]
 [29 10 24]
 [29 32 21]]

Разность А - В:
[[  0  -9   1]
 [  5   0  12]
 [  1  -8 -11]]

Поэлементное произведение:
[[ 25  70 156]
 [204  25 108]
 [210 240  80]]


In [7]:
import numpy as np
A = np.random.randint(1, 11, (2, 3))
print("Матрица А (2x3):")
print(A)

B = np.random.randint(1, 11, (3, 2))
print("\nМатрица В (3x2):")
print(B)

result = np.dot(A, B)
print("\nРезультат умножения А * В (2x2):")
print(result)


Матрица А (2x3):
[[2 1 9]
 [3 5 1]]

Матрица В (3x2):
[[9 8]
 [9 7]
 [3 6]]

Результат умножения А * В (2x2):
[[54 77]
 [75 65]]


In [8]:
import numpy as np
A = np.random.rand(3, 3)
print("Матрица А:")
print(A)

opr = np.linalg.det(A)
print(f"\nОпределитель матрицы: {opr:.4f}")

if opr == 0:
    print("\nМатрица вырождена")
else:
    opr = np.linalg.inv(A)
    print("\nОбратная матрица:\n", opr)

Матрица А:
[[0.82585928 0.75867799 0.78908712]
 [0.29914602 0.70169447 0.33549561]
 [0.5357041  0.1513385  0.76917366]]

Определитель матрицы: 0.1047

Обратная матрица:
 [[ 4.6701638  -4.43314015 -2.85743927]
 [-0.48109235  2.02978388 -0.39179684]
 [-3.15795796  2.68816654  3.36729661]]


In [9]:
import numpy as np
A = np.random.randint(1, 51, (4, 4))
print("Матрица 4x4:")
print(A)

transposed = np.transpose(A)
print("\nТранспонированная матрица:")
print(transposed)

trace = np.trace(A)
print(f"\nСлед матрицы: {trace}")

Матрица 4x4:
[[49 32 40 39]
 [41 34  8 18]
 [ 4 32  1 19]
 [29  3 26 34]]

Транспонированная матрица:
[[49 41  4 29]
 [32 34 32  3]
 [40  8  1 26]
 [39 18 19 34]]

След матрицы: 118


In [10]:
import numpy as np


A = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
B = np.array([[5], [6], [-2]])

print("Матрица коэффициентов А:")
print(A)
print("\nВектор правой части В:")
print(B)


res = np.linalg.solve(A, B)

print("\nРешение системы:")
print(f"x = {res[0][0]:.4f}")
print(f"y = {res[1][0]:.4f}")
print(f"z = {res[2][0]:.4f}")

Матрица коэффициентов А:
[[ 2  3 -1]
 [ 4 -1  2]
 [-3  5  4]]

Вектор правой части В:
[[ 5]
 [ 6]
 [-2]]

Решение системы:
x = 1.6396
y = 0.5766
z = 0.0090
