<a href="https://colab.research.google.com/github/truebobsuncle/IE2/blob/main/Indiv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([[1, 1, 1], [1, -2, 0], [0, -1, 1]], dtype=float)
B = np.array([1000000, 0, 200000], dtype=float)

A_inv = np.linalg.inv(A)
res_matrix = A_inv.dot(B)
print(res_matrix)

det_A = np.linalg.det(A)
A1 = A.copy(); A1[:, 0] = B
A2 = A.copy(); A2[:, 1] = B
A3 = A.copy(); A3[:, 2] = B

x_kramer = np.linalg.det(A1) / det_A
y_kramer = np.linalg.det(A2) / det_A
z_kramer = np.linalg.det(A3) / det_A
print(np.array([x_kramer, y_kramer, z_kramer]))

res_solve = np.linalg.solve(A, B)
print(res_solve)

[400000. 200000. 400000.]
[400000. 200000. 400000.]
[400000. 200000. 400000.]
